export const themes = {
  light: {
    background: "#f9f9f9",
    backgroundSecondary: "#fff",
    text: "#000",
    textSecondary: "#595959",
    primary: "#2E8B57",
    primaryText: "#fff",
    border: "#f2f2f2",
    modalOverlay: "rgba(0, 0, 0, 0.5)",
    icon: "#595959",
    addButton: "#2E8B57",
    addButtonText: "#fff",
    textInputBG: "#f5f5f5",
    cancelButtonBG: "#f5f5f5",
    cancelButtonText: "#000",
  },
  dark: {
    background: "#121212",
    backgroundSecondary: "#1e1e1e",
    text: "#fff",
    textSecondary: "#a5a5a5",
    primary: "#2E8B57",
    primaryText: "#fff",
    border: "#2e2e2e",
    modalOverlay: "rgba(0, 0, 0, 0.7)",
    icon: "#a5a5a5",
    addButton: "#2E8B57",
    addButtonText: "#fff",
    textInputBG: "#2e2e2e",
    cancelButtonBG: "#2e2e2e",
    cancelButtonText: "#fff",
  },
};
